### ISSUE TITLE
def print(self) SyntaxError

### ISSUE THREAD

**Issue by Birdy3000** [alvinwan/tex2py#10]
Traceback (most recent call last):
  File "/Users/id/PycharmProjects/op3/do_it.py", line 1, in <module>
    from tex2py import tex2py
  File "/Library/Python/2.7/site-packages/tex2py/__init__.py", line 1, in <module>
    from tex2py.tex2py import TreeOfContents
  File "/Library/Python/2.7/site-packages/tex2py/tex2py.py", line 212
    def print(self):
            ^
SyntaxError: invalid syntax

This error occurs, when you simply try out the sample tex document on the documentation page.

**Comment by juancq** [comment]
This is more of a documentation issue. I ran into this issue as well. As far as I'm aware, python 2.7 is not supported. If you run it with python3 it will run without errors. Maybe the README should be explicit and clear that python 2.7 is not supported.

**Comment by alvinwan** [comment]
thanks for the heads up, README updated

**Comment by ninijoe** [comment]
hi i ran this with python 3 and i am still getting the same errors
