### ISSUE TITLE
toc.section returns None when running the example chikin.tex

### ISSUE THREAD

**Issue by ErikThorsell** [alvinwan/tex2py#12]
# Issue
When trying out tex2py, traversing the toc of the chikin.tex-example, `toc.section` returns `None`.

# Steps to reproduce
```
with open("chikin.tex", 'r') as f:
  data = f.read()
  toc = tex2py(data)

  print(toc.section)
  print(str(toc.section))
```
Yields:
```
None
None
```

# Expected behaviour
Should print `Chikin Tales` and `'Chickin Tales'` respectively (?)

# Noteworthy
```
with open("chikin.tex", 'r') as f:
  data = f.read()
  toc = tex2py(data)
  soup = toc.source

  sections = soup.find_all('section')
  for s in sections:
    print(s)
```
Prints
```
\section{Chikin Tales}
\section{Chikin Scream}
```
as expected.

# What I want
I want to be able to generate the order of the sections/subsections/subsubsections/... in a LaTeX document. That is, if my .tex-file has the following structure:
```
\section{A}
text
\subsection{AA}
text
\section{B}
text
\section{C}
text
\subsection{CA}
text
```
I want to be able to tell which subsection belongs to which section, as well as recalling which text belongs to which (sub)section.

 It is my understanding that this should be doable using tex2py. If I can achive the same result using only TexSoup, I am willing to try.

Thank you.

**Comment by alvinwan** [comment]
Ah, my mistake. Forgot to deploy to PyPi. Thanks for taking the time to write a detailed issue.

Just deployed and tested; the latest release `0.0.4` fixes it, but feel free to reopen if that doesn't do it:

```
(env3) [alvin]$ pip list | grep tex2py
tex2py (0.0.4)
(env3) [alvin]$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tex2py import tex2py
>>> with open("chikin.tex", 'r') as f:
...   data = f.read()
...   toc = tex2py(data)
...
>>> print(toc.section)
Chikin Tales
>>> print(str(toc.section))
Chikin Tales
>>>
```

**Comment by superhans** [comment]
I'm unable to reproduce the examples in README.md

When I do : `list(toc.section.subsections)`, I get only one of the subsections
```
>>> list(toc.section.subsections)
[Chikin Fly]
```

When I do `toc.section[1]`, I get 
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tex2py/tex2py.py", line 206, in __getitem__
    return self.branches[i]
IndexError: list index out of range

```
