### ISSUE TITLE
missin requirements.txt ?

### ISSUE THREAD

**Issue by pazz** [alvinwan/tex2py#6]
I get the following error when trying to install..
```
pip install --user tex2py  
Collecting tex2py
  Using cached tex2py-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w9_Tek/tex2py/setup.py", line 7, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w9_Tek/tex2py/

```

```
pip --version
pip 9.0.1 from /home/pazz/.local/lib/python2.7/site-packages (python 2.7)
```

**Comment by alvinwan** [comment]
@pazz my bad @tarohi24 actually fixed this in #4 but I never got around to pushing a new version to pip. will work on that

**Comment by pazz** [comment]
Oh silly me! I didn't check the issues.. never mind then and thanks,
p

**Comment by Rested** [comment]
Hey just as a heads up, still getting this issue!

**Comment by alvinwan** [comment]
Thanks for reporting - sorry it took so long!

**Comment by juancq** [comment]
Another heads up, still getting this issue.

**Comment by ErikThorsell** [comment]
Aaand, still getting the issue.

**Comment by alvinwan** [comment]
Ack sorry, I never uploaded the dist. Just fixed. @ErikThorsell Just wanted to confirm if it works for you?

**Comment by alvinwan** [comment]
Please feel free to reopen if still not fixed. My mistake.
