### ISSUE TITLE
AttributeError in __str__ when calling print() method

### ISSUE THREAD

**Issue by juancq** [alvinwan/tex2py#9]
I'm calling print as follows:
soup = tex2py(open(fname).read())
soup.print()

And getting the following error:
.../tex2py.py, line 203, in \_\_str\_\_
    return self.string or self.root or ''
  File ".../tex2py/tex2py.py", line 187, in \_\_getattr\_\_
    return getattr(self.source, attr, *default)
AttributeError: 'RArg' object has no attribute 'string'

Changed tex2py as follows to make error go away, but I'm uncertain about resulting side-effects:
if getattr(self, 'string', False):
   return self.string
elif getattr(self, 'root', False):
   return self.root
else:
   return ''

**Comment by alvinwan** [comment]
Mm, it should work now. I had another bug - please feel free to reopen if not fixed

**Comment by juancq** [comment]
I'm still getting the error. You can generate the error with chickin.tex and calling soup.print()

**Comment by alvinwan** [comment]
Got it, I ended up making changes to `TexSoup` too. If you install developer versions of `TexSoup` master and `tex2py` master, it should work. I'll circle back to see if you find otherwise.
